services:
  - type: web
    name: sanos-salvos-api-pets
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /api/pets/stats
    envVars:
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        sync: false
      - key: RABBITMQ_URL
        sync: false
